### ISSUE TITLE
How to work ?

### ISSUE THREAD

**Issue by Geng812** [maxwellbkwt/projstock#2]
what is project goal?
how to work ?

**Comment by Geng812** [comment]
analysis reference :
http://www.cmoney.tw/notes/note-detail.aspx?nid=15701

**Comment by maxwellbkwt** [comment]
Project goal: 
1. Select candidate stock
2. Timing to pull in
3. History traceback
 
Data phaser to collect stock price information

**Comment by maxwellbkwt** [comment]
Ref: by pandas chose target
https://www.finlab.tw/Python%EF%BC%9A%E5%88%A9%E7%94%A8Pandas%E8%BC%95%E9%AC%86%E9%81%B8%E8%82%A1/

**Comment by Geng812** [comment]
Ref: 
https://github.com/toomore/grs

**Comment by maxwellbkwt** [comment]
> how to handle dedupe

Duplicated data? or what?

**Comment by maxwellbkwt** [comment]
from dataparse import get_webmsg
test123=get_webmsg(2018,10,2454)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/blackwhite/PycharmProjects/projstock/dataparse.py", line 6, in get_webmsg
    date = str (year) + "{0:0=2d}".format(month) +'01' ## format is yyyymmdd
UnboundLocalError: local variable 'date' referenced before assignment
year=2018
month=10
date = str (year) + "{0:0=2d}".format(month) +'01' 
date
'20181001'
sid=str(2454)
url_twse = 'http://www.twse.com.tw/exchangeReport/STOCK_DAY?response=json&date=' + date + '&stockNo=' + sid

**Comment by Geng812** [comment]
i test dataparse code is work , you fix out ?
